### ISSUE TITLE
How do I "complete" a request?

### ISSUE THREAD

**Issue by ccheever** [ide/hapi-async-handler#1]
All the endpoints I make this way that I load through a browser seem to spin endlessly, even if I say `response = reply someHtml`. How do I make it tell the client that it is done sending stuff?

**Comment by ide** [comment]
Calling `reply` should be enough for Hapi to send the response on nextTick. Could there be an error before the reply call? Right now any uncaught errors are logged through Hapi with the tags "request", "error", and "uncaught" and can be picked up with [good](https://github.com/hapijs/good).

**Comment by ccheever** [comment]
weird. i think the problem is that my internet was being really flaky -- i was seeing the log errors from good about the promises being around too long without being resolved, but they didn't have any real explanation.
