### ISSUE TITLE
Context is destroyed when handler is an async class function

### ISSUE THREAD

**Issue by skelet00r** [ide/hapi-async-handler#11]
```javascript
// someClass.js
module.exports = class someClass {
  constructor (options) {
    this.example = options.example
  }

  async handler(request, reply) {
    console.log(this) // undefined
  }
}

// route.js
const SomeClass = require('./someClass')
const someClass = new SomeClass('example data')

module.exports = [{
  method: 'GET',
  path: '/',
  handler: {
    async: someClass.handler
  }
}]
```

The issue is from calling the function with the context of the plugin. 
https://github.com/ide/hapi-async-handler/blob/33458cb3fe1f4d7813a14d86d8dccc6d709d99e5/src/index.js#L9

I cant think of a quick and clean way to solve this. You cant just pass `asyncHandler` as the context in place of `this`.(pretty sure)

Im thinking something along these lines:
```javascript
module.exports = [{
  method: 'GET',
  path: '/',
  handler: {
    async: {
        handler: someClass.handler,
        context: someClass
    }
  }
},{
  method: 'GET',
  path: '/other',
  handler: {
    async: someOtherAsyncHandler
  }
}]
```

This way backwards compatibility is in place and doesnt break the plugin for previous versions. Unless anyone has any suggestions on a cleaner way.

**Comment by ide** [comment]
As I commented on the PR, could you use bind() or pass in a closure that calls someClass.handler(...arguments)?

**Comment by skelet00r** [comment]
I don't even know why I didn't think of bind... 😕 

Bind is a better solution to my much more bloated suggestion

``` javascript
module.exports = [{
  method: 'GET',
  path: '/',
  handler: {
    async: someClass.handler.bind(someClass)
  }
}];
```

Much cleaner and works with `asyncHandler.call`
